
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PointOfInterest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PointOfInterest
 * 
 */
export type PointOfInterestModel = runtime.Types.Result.DefaultSelection<Prisma.$PointOfInterestPayload>

export type AggregatePointOfInterest = {
  _count: PointOfInterestCountAggregateOutputType | null
  _avg: PointOfInterestAvgAggregateOutputType | null
  _sum: PointOfInterestSumAggregateOutputType | null
  _min: PointOfInterestMinAggregateOutputType | null
  _max: PointOfInterestMaxAggregateOutputType | null
}

export type PointOfInterestAvgAggregateOutputType = {
  id: number | null
  lat: number | null
  lng: number | null
}

export type PointOfInterestSumAggregateOutputType = {
  id: number | null
  lat: number | null
  lng: number | null
}

export type PointOfInterestMinAggregateOutputType = {
  id: number | null
  name: string | null
  category: $Enums.PoiCategory | null
  description: string | null
  imageUrl: string | null
  lat: number | null
  lng: number | null
}

export type PointOfInterestMaxAggregateOutputType = {
  id: number | null
  name: string | null
  category: $Enums.PoiCategory | null
  description: string | null
  imageUrl: string | null
  lat: number | null
  lng: number | null
}

export type PointOfInterestCountAggregateOutputType = {
  id: number
  name: number
  category: number
  description: number
  imageUrl: number
  lat: number
  lng: number
  _all: number
}


export type PointOfInterestAvgAggregateInputType = {
  id?: true
  lat?: true
  lng?: true
}

export type PointOfInterestSumAggregateInputType = {
  id?: true
  lat?: true
  lng?: true
}

export type PointOfInterestMinAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  imageUrl?: true
  lat?: true
  lng?: true
}

export type PointOfInterestMaxAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  imageUrl?: true
  lat?: true
  lng?: true
}

export type PointOfInterestCountAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  imageUrl?: true
  lat?: true
  lng?: true
  _all?: true
}

export type PointOfInterestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointOfInterest to aggregate.
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointOfInterests to fetch.
   */
  orderBy?: Prisma.PointOfInterestOrderByWithRelationInput | Prisma.PointOfInterestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PointOfInterestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointOfInterests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointOfInterests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PointOfInterests
  **/
  _count?: true | PointOfInterestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PointOfInterestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PointOfInterestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PointOfInterestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PointOfInterestMaxAggregateInputType
}

export type GetPointOfInterestAggregateType<T extends PointOfInterestAggregateArgs> = {
      [P in keyof T & keyof AggregatePointOfInterest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePointOfInterest[P]>
    : Prisma.GetScalarType<T[P], AggregatePointOfInterest[P]>
}




export type PointOfInterestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PointOfInterestWhereInput
  orderBy?: Prisma.PointOfInterestOrderByWithAggregationInput | Prisma.PointOfInterestOrderByWithAggregationInput[]
  by: Prisma.PointOfInterestScalarFieldEnum[] | Prisma.PointOfInterestScalarFieldEnum
  having?: Prisma.PointOfInterestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PointOfInterestCountAggregateInputType | true
  _avg?: PointOfInterestAvgAggregateInputType
  _sum?: PointOfInterestSumAggregateInputType
  _min?: PointOfInterestMinAggregateInputType
  _max?: PointOfInterestMaxAggregateInputType
}

export type PointOfInterestGroupByOutputType = {
  id: number
  name: string
  category: $Enums.PoiCategory
  description: string | null
  imageUrl: string | null
  lat: number
  lng: number
  _count: PointOfInterestCountAggregateOutputType | null
  _avg: PointOfInterestAvgAggregateOutputType | null
  _sum: PointOfInterestSumAggregateOutputType | null
  _min: PointOfInterestMinAggregateOutputType | null
  _max: PointOfInterestMaxAggregateOutputType | null
}

export type GetPointOfInterestGroupByPayload<T extends PointOfInterestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PointOfInterestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PointOfInterestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PointOfInterestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PointOfInterestGroupByOutputType[P]>
      }
    >
  >



export type PointOfInterestWhereInput = {
  AND?: Prisma.PointOfInterestWhereInput | Prisma.PointOfInterestWhereInput[]
  OR?: Prisma.PointOfInterestWhereInput[]
  NOT?: Prisma.PointOfInterestWhereInput | Prisma.PointOfInterestWhereInput[]
  id?: Prisma.IntFilter<"PointOfInterest"> | number
  name?: Prisma.StringFilter<"PointOfInterest"> | string
  category?: Prisma.EnumPoiCategoryFilter<"PointOfInterest"> | $Enums.PoiCategory
  description?: Prisma.StringNullableFilter<"PointOfInterest"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"PointOfInterest"> | string | null
  lat?: Prisma.FloatFilter<"PointOfInterest"> | number
  lng?: Prisma.FloatFilter<"PointOfInterest"> | number
}

export type PointOfInterestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type PointOfInterestWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PointOfInterestWhereInput | Prisma.PointOfInterestWhereInput[]
  OR?: Prisma.PointOfInterestWhereInput[]
  NOT?: Prisma.PointOfInterestWhereInput | Prisma.PointOfInterestWhereInput[]
  name?: Prisma.StringFilter<"PointOfInterest"> | string
  category?: Prisma.EnumPoiCategoryFilter<"PointOfInterest"> | $Enums.PoiCategory
  description?: Prisma.StringNullableFilter<"PointOfInterest"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"PointOfInterest"> | string | null
  lat?: Prisma.FloatFilter<"PointOfInterest"> | number
  lng?: Prisma.FloatFilter<"PointOfInterest"> | number
}, "id">

export type PointOfInterestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
  _count?: Prisma.PointOfInterestCountOrderByAggregateInput
  _avg?: Prisma.PointOfInterestAvgOrderByAggregateInput
  _max?: Prisma.PointOfInterestMaxOrderByAggregateInput
  _min?: Prisma.PointOfInterestMinOrderByAggregateInput
  _sum?: Prisma.PointOfInterestSumOrderByAggregateInput
}

export type PointOfInterestScalarWhereWithAggregatesInput = {
  AND?: Prisma.PointOfInterestScalarWhereWithAggregatesInput | Prisma.PointOfInterestScalarWhereWithAggregatesInput[]
  OR?: Prisma.PointOfInterestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PointOfInterestScalarWhereWithAggregatesInput | Prisma.PointOfInterestScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PointOfInterest"> | number
  name?: Prisma.StringWithAggregatesFilter<"PointOfInterest"> | string
  category?: Prisma.EnumPoiCategoryWithAggregatesFilter<"PointOfInterest"> | $Enums.PoiCategory
  description?: Prisma.StringNullableWithAggregatesFilter<"PointOfInterest"> | string | null
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"PointOfInterest"> | string | null
  lat?: Prisma.FloatWithAggregatesFilter<"PointOfInterest"> | number
  lng?: Prisma.FloatWithAggregatesFilter<"PointOfInterest"> | number
}

export type PointOfInterestCreateInput = {
  name: string
  category: $Enums.PoiCategory
  description?: string | null
  imageUrl?: string | null
  lat: number
  lng: number
}

export type PointOfInterestUncheckedCreateInput = {
  id?: number
  name: string
  category: $Enums.PoiCategory
  description?: string | null
  imageUrl?: string | null
  lat: number
  lng: number
}

export type PointOfInterestUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumPoiCategoryFieldUpdateOperationsInput | $Enums.PoiCategory
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lng?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PointOfInterestUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumPoiCategoryFieldUpdateOperationsInput | $Enums.PoiCategory
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lng?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PointOfInterestCreateManyInput = {
  id?: number
  name: string
  category: $Enums.PoiCategory
  description?: string | null
  imageUrl?: string | null
  lat: number
  lng: number
}

export type PointOfInterestUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumPoiCategoryFieldUpdateOperationsInput | $Enums.PoiCategory
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lng?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PointOfInterestUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumPoiCategoryFieldUpdateOperationsInput | $Enums.PoiCategory
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lat?: Prisma.FloatFieldUpdateOperationsInput | number
  lng?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PointOfInterestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type PointOfInterestAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type PointOfInterestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type PointOfInterestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type PointOfInterestSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type EnumPoiCategoryFieldUpdateOperationsInput = {
  set?: $Enums.PoiCategory
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type PointOfInterestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  imageUrl?: boolean
  lat?: boolean
  lng?: boolean
}, ExtArgs["result"]["pointOfInterest"]>

export type PointOfInterestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  imageUrl?: boolean
  lat?: boolean
  lng?: boolean
}, ExtArgs["result"]["pointOfInterest"]>

export type PointOfInterestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  imageUrl?: boolean
  lat?: boolean
  lng?: boolean
}, ExtArgs["result"]["pointOfInterest"]>

export type PointOfInterestSelectScalar = {
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  imageUrl?: boolean
  lat?: boolean
  lng?: boolean
}

export type PointOfInterestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "category" | "description" | "imageUrl" | "lat" | "lng", ExtArgs["result"]["pointOfInterest"]>

export type $PointOfInterestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PointOfInterest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    category: $Enums.PoiCategory
    description: string | null
    imageUrl: string | null
    lat: number
    lng: number
  }, ExtArgs["result"]["pointOfInterest"]>
  composites: {}
}

export type PointOfInterestGetPayload<S extends boolean | null | undefined | PointOfInterestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload, S>

export type PointOfInterestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PointOfInterestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PointOfInterestCountAggregateInputType | true
  }

export interface PointOfInterestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PointOfInterest'], meta: { name: 'PointOfInterest' } }
  /**
   * Find zero or one PointOfInterest that matches the filter.
   * @param {PointOfInterestFindUniqueArgs} args - Arguments to find a PointOfInterest
   * @example
   * // Get one PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PointOfInterestFindUniqueArgs>(args: Prisma.SelectSubset<T, PointOfInterestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PointOfInterest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PointOfInterestFindUniqueOrThrowArgs} args - Arguments to find a PointOfInterest
   * @example
   * // Get one PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PointOfInterestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PointOfInterestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointOfInterest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestFindFirstArgs} args - Arguments to find a PointOfInterest
   * @example
   * // Get one PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PointOfInterestFindFirstArgs>(args?: Prisma.SelectSubset<T, PointOfInterestFindFirstArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointOfInterest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestFindFirstOrThrowArgs} args - Arguments to find a PointOfInterest
   * @example
   * // Get one PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PointOfInterestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PointOfInterestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PointOfInterests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PointOfInterests
   * const pointOfInterests = await prisma.pointOfInterest.findMany()
   * 
   * // Get first 10 PointOfInterests
   * const pointOfInterests = await prisma.pointOfInterest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pointOfInterestWithIdOnly = await prisma.pointOfInterest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PointOfInterestFindManyArgs>(args?: Prisma.SelectSubset<T, PointOfInterestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PointOfInterest.
   * @param {PointOfInterestCreateArgs} args - Arguments to create a PointOfInterest.
   * @example
   * // Create one PointOfInterest
   * const PointOfInterest = await prisma.pointOfInterest.create({
   *   data: {
   *     // ... data to create a PointOfInterest
   *   }
   * })
   * 
   */
  create<T extends PointOfInterestCreateArgs>(args: Prisma.SelectSubset<T, PointOfInterestCreateArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PointOfInterests.
   * @param {PointOfInterestCreateManyArgs} args - Arguments to create many PointOfInterests.
   * @example
   * // Create many PointOfInterests
   * const pointOfInterest = await prisma.pointOfInterest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PointOfInterestCreateManyArgs>(args?: Prisma.SelectSubset<T, PointOfInterestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PointOfInterests and returns the data saved in the database.
   * @param {PointOfInterestCreateManyAndReturnArgs} args - Arguments to create many PointOfInterests.
   * @example
   * // Create many PointOfInterests
   * const pointOfInterest = await prisma.pointOfInterest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PointOfInterests and only return the `id`
   * const pointOfInterestWithIdOnly = await prisma.pointOfInterest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PointOfInterestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PointOfInterestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PointOfInterest.
   * @param {PointOfInterestDeleteArgs} args - Arguments to delete one PointOfInterest.
   * @example
   * // Delete one PointOfInterest
   * const PointOfInterest = await prisma.pointOfInterest.delete({
   *   where: {
   *     // ... filter to delete one PointOfInterest
   *   }
   * })
   * 
   */
  delete<T extends PointOfInterestDeleteArgs>(args: Prisma.SelectSubset<T, PointOfInterestDeleteArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PointOfInterest.
   * @param {PointOfInterestUpdateArgs} args - Arguments to update one PointOfInterest.
   * @example
   * // Update one PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PointOfInterestUpdateArgs>(args: Prisma.SelectSubset<T, PointOfInterestUpdateArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PointOfInterests.
   * @param {PointOfInterestDeleteManyArgs} args - Arguments to filter PointOfInterests to delete.
   * @example
   * // Delete a few PointOfInterests
   * const { count } = await prisma.pointOfInterest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PointOfInterestDeleteManyArgs>(args?: Prisma.SelectSubset<T, PointOfInterestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointOfInterests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PointOfInterests
   * const pointOfInterest = await prisma.pointOfInterest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PointOfInterestUpdateManyArgs>(args: Prisma.SelectSubset<T, PointOfInterestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointOfInterests and returns the data updated in the database.
   * @param {PointOfInterestUpdateManyAndReturnArgs} args - Arguments to update many PointOfInterests.
   * @example
   * // Update many PointOfInterests
   * const pointOfInterest = await prisma.pointOfInterest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PointOfInterests and only return the `id`
   * const pointOfInterestWithIdOnly = await prisma.pointOfInterest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PointOfInterestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PointOfInterestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PointOfInterest.
   * @param {PointOfInterestUpsertArgs} args - Arguments to update or create a PointOfInterest.
   * @example
   * // Update or create a PointOfInterest
   * const pointOfInterest = await prisma.pointOfInterest.upsert({
   *   create: {
   *     // ... data to create a PointOfInterest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PointOfInterest we want to update
   *   }
   * })
   */
  upsert<T extends PointOfInterestUpsertArgs>(args: Prisma.SelectSubset<T, PointOfInterestUpsertArgs<ExtArgs>>): Prisma.Prisma__PointOfInterestClient<runtime.Types.Result.GetResult<Prisma.$PointOfInterestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PointOfInterests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestCountArgs} args - Arguments to filter PointOfInterests to count.
   * @example
   * // Count the number of PointOfInterests
   * const count = await prisma.pointOfInterest.count({
   *   where: {
   *     // ... the filter for the PointOfInterests we want to count
   *   }
   * })
  **/
  count<T extends PointOfInterestCountArgs>(
    args?: Prisma.Subset<T, PointOfInterestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PointOfInterestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PointOfInterest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PointOfInterestAggregateArgs>(args: Prisma.Subset<T, PointOfInterestAggregateArgs>): Prisma.PrismaPromise<GetPointOfInterestAggregateType<T>>

  /**
   * Group by PointOfInterest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointOfInterestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PointOfInterestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PointOfInterestGroupByArgs['orderBy'] }
      : { orderBy?: PointOfInterestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PointOfInterestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPointOfInterestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PointOfInterest model
 */
readonly fields: PointOfInterestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PointOfInterest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PointOfInterestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PointOfInterest model
 */
export interface PointOfInterestFieldRefs {
  readonly id: Prisma.FieldRef<"PointOfInterest", 'Int'>
  readonly name: Prisma.FieldRef<"PointOfInterest", 'String'>
  readonly category: Prisma.FieldRef<"PointOfInterest", 'PoiCategory'>
  readonly description: Prisma.FieldRef<"PointOfInterest", 'String'>
  readonly imageUrl: Prisma.FieldRef<"PointOfInterest", 'String'>
  readonly lat: Prisma.FieldRef<"PointOfInterest", 'Float'>
  readonly lng: Prisma.FieldRef<"PointOfInterest", 'Float'>
}
    

// Custom InputTypes
/**
 * PointOfInterest findUnique
 */
export type PointOfInterestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter, which PointOfInterest to fetch.
   */
  where: Prisma.PointOfInterestWhereUniqueInput
}

/**
 * PointOfInterest findUniqueOrThrow
 */
export type PointOfInterestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter, which PointOfInterest to fetch.
   */
  where: Prisma.PointOfInterestWhereUniqueInput
}

/**
 * PointOfInterest findFirst
 */
export type PointOfInterestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter, which PointOfInterest to fetch.
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointOfInterests to fetch.
   */
  orderBy?: Prisma.PointOfInterestOrderByWithRelationInput | Prisma.PointOfInterestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointOfInterests.
   */
  cursor?: Prisma.PointOfInterestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointOfInterests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointOfInterests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointOfInterests.
   */
  distinct?: Prisma.PointOfInterestScalarFieldEnum | Prisma.PointOfInterestScalarFieldEnum[]
}

/**
 * PointOfInterest findFirstOrThrow
 */
export type PointOfInterestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter, which PointOfInterest to fetch.
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointOfInterests to fetch.
   */
  orderBy?: Prisma.PointOfInterestOrderByWithRelationInput | Prisma.PointOfInterestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointOfInterests.
   */
  cursor?: Prisma.PointOfInterestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointOfInterests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointOfInterests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointOfInterests.
   */
  distinct?: Prisma.PointOfInterestScalarFieldEnum | Prisma.PointOfInterestScalarFieldEnum[]
}

/**
 * PointOfInterest findMany
 */
export type PointOfInterestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter, which PointOfInterests to fetch.
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointOfInterests to fetch.
   */
  orderBy?: Prisma.PointOfInterestOrderByWithRelationInput | Prisma.PointOfInterestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PointOfInterests.
   */
  cursor?: Prisma.PointOfInterestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointOfInterests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointOfInterests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointOfInterests.
   */
  distinct?: Prisma.PointOfInterestScalarFieldEnum | Prisma.PointOfInterestScalarFieldEnum[]
}

/**
 * PointOfInterest create
 */
export type PointOfInterestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * The data needed to create a PointOfInterest.
   */
  data: Prisma.XOR<Prisma.PointOfInterestCreateInput, Prisma.PointOfInterestUncheckedCreateInput>
}

/**
 * PointOfInterest createMany
 */
export type PointOfInterestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PointOfInterests.
   */
  data: Prisma.PointOfInterestCreateManyInput | Prisma.PointOfInterestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PointOfInterest createManyAndReturn
 */
export type PointOfInterestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * The data used to create many PointOfInterests.
   */
  data: Prisma.PointOfInterestCreateManyInput | Prisma.PointOfInterestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PointOfInterest update
 */
export type PointOfInterestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * The data needed to update a PointOfInterest.
   */
  data: Prisma.XOR<Prisma.PointOfInterestUpdateInput, Prisma.PointOfInterestUncheckedUpdateInput>
  /**
   * Choose, which PointOfInterest to update.
   */
  where: Prisma.PointOfInterestWhereUniqueInput
}

/**
 * PointOfInterest updateMany
 */
export type PointOfInterestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PointOfInterests.
   */
  data: Prisma.XOR<Prisma.PointOfInterestUpdateManyMutationInput, Prisma.PointOfInterestUncheckedUpdateManyInput>
  /**
   * Filter which PointOfInterests to update
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * Limit how many PointOfInterests to update.
   */
  limit?: number
}

/**
 * PointOfInterest updateManyAndReturn
 */
export type PointOfInterestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * The data used to update PointOfInterests.
   */
  data: Prisma.XOR<Prisma.PointOfInterestUpdateManyMutationInput, Prisma.PointOfInterestUncheckedUpdateManyInput>
  /**
   * Filter which PointOfInterests to update
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * Limit how many PointOfInterests to update.
   */
  limit?: number
}

/**
 * PointOfInterest upsert
 */
export type PointOfInterestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * The filter to search for the PointOfInterest to update in case it exists.
   */
  where: Prisma.PointOfInterestWhereUniqueInput
  /**
   * In case the PointOfInterest found by the `where` argument doesn't exist, create a new PointOfInterest with this data.
   */
  create: Prisma.XOR<Prisma.PointOfInterestCreateInput, Prisma.PointOfInterestUncheckedCreateInput>
  /**
   * In case the PointOfInterest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PointOfInterestUpdateInput, Prisma.PointOfInterestUncheckedUpdateInput>
}

/**
 * PointOfInterest delete
 */
export type PointOfInterestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
  /**
   * Filter which PointOfInterest to delete.
   */
  where: Prisma.PointOfInterestWhereUniqueInput
}

/**
 * PointOfInterest deleteMany
 */
export type PointOfInterestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointOfInterests to delete
   */
  where?: Prisma.PointOfInterestWhereInput
  /**
   * Limit how many PointOfInterests to delete.
   */
  limit?: number
}

/**
 * PointOfInterest without action
 */
export type PointOfInterestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointOfInterest
   */
  select?: Prisma.PointOfInterestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointOfInterest
   */
  omit?: Prisma.PointOfInterestOmit<ExtArgs> | null
}
